modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "galaxylib"
version = "1.0.0"
displayName = "GalaxyLib"
authors = "Galaxy Team"
description = '''Shared runtime APIs and systems for VerShift modules.'''

[[dependencies."galaxylib"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."galaxylib"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1, 1.22)"
ordering = "NONE"
side = "BOTH"

