plugins{
    id 'net.neoforged.moddev' version '2.0.88' apply false
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
        // 统一提供 Biotech 传递依赖所需仓库
        maven { url = 'https://maven.firstdark.dev/snapshots' }
        maven {
            name = 'Curios'
            url = uri('https://maven.theillusivec4.top/')
        }

        //spell book
        maven {
            name = "Iron's Maven - Release"
            url = "https://code.redspace.io/releases"
        }
        maven { url = "https://maven.kosmx.dev/" }
        maven { url = "https://maven.theillusivec4.top" }

        maven {
            url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
            content {
                includeGroup("software.bernie.geckolib")
            }
        }
        // better combat
        maven { url 'https://api.modrinth.com/maven' }
        maven { url "https://maven.shedaniel.me/" }
        maven {
            name = "FzzyMaven"
            url = "https://maven.fzzyhmstrs.me/"
        }
        maven {
            url = "https://thedarkcolour.github.io/KotlinForForge/"
        }
        maven {
            url "https://maven.twelveiterations.com/repository/maven-public/"

            content {
                includeGroup "net.blay09.mods"
            }
        }
        maven { url = "https://cursemaven.com" }


    }
}

subprojects {
    plugins.withId('java') {
        dependencies {
            compileOnly("org.projectlombok:lombok:${dep_lombok_version}")
            annotationProcessor("org.projectlombok:lombok:${dep_lombok_version}")
            testCompileOnly("org.projectlombok:lombok:${dep_lombok_version}")
            testAnnotationProcessor("org.projectlombok:lombok:${dep_lombok_version}")
        }
    }
}

