plugins{
    id 'net.neoforged.moddev' version '2.0.88' apply false
}

allprojects {
    repositories {
        mavenLocal()
        maven { url = 'https://maven.neoforged.net/releases' }
        // 统一提供 Biotech 传递依赖所需仓库
        maven { url = 'https://maven.firstdark.dev/snapshots' }
        maven {
            name = 'Curios'
            url = uri('https://maven.theillusivec4.top/')
        }
    }
}

subprojects {
    plugins.withId('java') {
        dependencies {
            compileOnly("org.projectlombok:lombok:${dep_lombok_version}")
            annotationProcessor("org.projectlombok:lombok:${dep_lombok_version}")
            testCompileOnly("org.projectlombok:lombok:${dep_lombok_version}")
            testAnnotationProcessor("org.projectlombok:lombok:${dep_lombok_version}")
        }
    }
}

