plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev'
}

version = mod_version
group = mod_group_id

def galaxyLib = project(":GalaxyLib")
def beyond = project(":Beyond")
def biotech = project(":Biotech")

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version
    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation(galaxyLib)
    implementation(beyond)
    implementation(biotech)

    //spell book
    implementation "io.redspace:irons_spellbooks:${iron_mod}"
    implementation "io.redspace:irons_lib:${irons_lib_version}"
    implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    implementation "dev.kosmx.player-anim:player-animation-lib-forge:${player_animator_version}"
    implementation "top.theillusivec4.curios:curios-neoforge:${dep_curios_version}"

    //better combat
    implementation "maven.modrinth:better-combat:${better_combat_version}"
    api "me.shedaniel.cloth:cloth-config-${cloth_config_version}"

    //Puzzles Lib
    implementation "maven.modrinth:puzzles-lib:${puzzles_Lib_version}"

    //simply_swords
    implementation("maven.modrinth:simply-swords:${simply_swords}")
    implementation("maven.modrinth:architectury-api:${architectury_api_version}")
    implementation("maven.modrinth:simply-tooltips:${simply_tooltips_version}")
    implementation("me.fzzyhmstrs:fzzy_config:${fzzy_config_version}")

    //lidlib 2 给这里也整上，毕竟很好用
    implementation("com.lowdragmc.ldlib2:ldlib2-neoforge-${minecraft_version}:${dep_ldlib2_version}:all")

    //永恒传送门（刷怪必备）
    implementation "maven.modrinth:gateways-to-eternity:1.21.1-5.1.0"
    implementation "maven.modrinth:apothic-attributes:1.21.1-2.10.1"
    implementation "maven.modrinth:placebo:1.21.1-9.9.2"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
